-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 16:41:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema protocols
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `protocols` ;

-- -----------------------------------------------------
-- Schema protocols
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `protocols` DEFAULT CHARACTER SET utf8 ;
USE `protocols` ;

-- -----------------------------------------------------
-- Table `protocols`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `protocols`.`subjects` ;

CREATE TABLE IF NOT EXISTS `protocols`.`subjects` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protocols`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `protocols`.`users` ;

CREATE TABLE IF NOT EXISTS `protocols`.`users` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `type` TINYINT(4) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protocols`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `protocols`.`requests` ;

CREATE TABLE IF NOT EXISTS `protocols`.`requests` (
  `subject_id` INT(10) NOT NULL,
  `users_id` INT(10) NOT NULL,
  `id` INT(10) NOT NULL,
  `description` BLOB NOT NULL,
  `date` DATE NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `requestscol` VARCHAR(45) NULL,
  INDEX `fk_subjects_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_subjects_has_users_subjects_idx` (`subject_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_subjects_has_users_subjects`
    FOREIGN KEY (`subject_id`)
    REFERENCES `protocols`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `protocols`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
